ceph/paddles

paddles/commands/queue_stats.py

Sample output, before and after:
```
(virtualenv)14:35:19 zack@zwork.local paddles master ? pecan queue_stats prod.py 7
No handlers could be found for logger "sqlalchemy.engine.base.Engine"
2015-01-29: 2013 scheduled, 1767 completed
2015-01-30: 1934 scheduled, 1843 completed
2015-01-31: 1331 scheduled, 1149 completed
2015-02-01: 1605 scheduled, 1448 completed
2015-02-02:  574 scheduled,  548 completed
2015-02-03: 1493 scheduled, 1368 completed
2015-02-04: 2553 scheduled, 1072 completed
(virtualenv)14:35:25 zack@zwork.local paddles master ? git checkout wip-queue-stats
Switched to branch 'wip-queue-stats'
(virtualenv)14:35:34 zack@zwork.local paddles wip-queue-stats ? pecan queue_stats prod.py 7
No handlers could be found for logger "sqlalchemy.engine.base.Engine"
2015-01-29: 2013 …
```

Add percentage to queue_stats command

---

paddles/models/nodes.py
paddles/tests/controllers/test_nodes.py

It was always a bad idea on multiple levels, but most importantly, it
can really confuse teuthology when it tries to lock and provision
downburst VMs.
http://tracker.ceph.com/issues/11808
Signed-off-by: Zack Cerza <zack@redhat.com>

Remove lock-recycling misfeature

---

paddles/commands/populate.py

That line triggers the bug: http://tracker.ceph.com/issues/13595
In earlier versions of pecan the models.init_model() was needed, but in
later versions it is not.
In looking at the differences between chacra's populate command and paddle's I noticed this commit:
https://github.com/ceph/chacra/commit/cd8ab6c108fc176f0a4872ea11394adc20a28a67
Unfortunately there is not much context on that commit, but removing that line here in paddles fixes the populate command.

remove unneeded models.init_model in commands/populate.py

---

paddles/commands/expire_jobs.py

Instead of hardcoding the 30m for running jobs and 14d for queued jobs,
make them arguments that can be passed on the command line.
Signed-off-by: Zack Cerza <zack@redhat.com>

Parametrize expiration intervals

---

README.rst
alembic/versions/4b86caad387e_add_ceph_and_ceph_qa_suite_fields.py
paddles/models/jobs.py

The three new fields (sha1, branch and suite_sha1) are indexed. They are
already present in the json job description that teuthology/report.py
sends to paddle, there does not need to be a modification teuthology
side.
Signed-off-by: Loic Dachary <loic@dachary.org>

models: jobs stores ceph/ceph-qa-suite branch and sha1

---

config.py.in
paddles/models/jobs.py
paddles/stats.py
paddles/tests/models/test_jobs.py
requirements.txt

statsd is optional and disabled by default. This code is already running on paddles.front.sepia.ceph.com

Submit pass/fail/dead job counts to statsd

---

requirements.txt

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>

requirements.txt: bump up psycopg2

---

requirements.txt

Fixes: https://nvd.nist.gov/vuln/detail/CVE-2018-1000164
Signed-off-by: Alfredo Deza <adeza@redhat.com>

bump gunicorn to 19.5.0 to avoid  CWE-113

---

.travis.yml

Commit ea5d3c245e58 introduced TravisCI but the yaml configuration was
wrong. Fix that now.
Signed-off-by: Thomas Bechtold <tbechtold@suse.com>

ci: Fix travis syntax error

---

config.py.in
paddles/tests/controllers/test_jobs_race.py

By default postgres uses the READ COMMITTED isolation level,
which allows transactions to read data that may be modified
concurrently by another transaction [0].
When teuthology queues a job, it adds it to beanstalkd, then
reports that new job id to paddles.  In handling this request,
paddles:
1) checks for a job with the same id
2) adds a new row in the jobs table for this job
On the server side, when teuthology-dispatcher reads from the
queue, it also updates the job status in paddles, going through
the same request handling as above.
When both requests are run simultaneously, both requests may do
step (1) and record no existing job, then both proceed to
step (2) and add a new row.
With SERIALIZABLE isolation, this is impossible - the 2nd
transaction will be aborted when the job is …

config.py.in: use SERIALIZABLE isolation level for the db

---

paddles/controllers/nodes.py
paddles/tests/controllers/test_read_write_dependency.py

After a read/write dependency occurs among transactions, we need to rollback and retry the requests.
Pecan takes care of rolling back all write requests (PUT/POST)  on error. However, this does not happen for the read requests.
This fix adds a session rollback and request retry for the GET requests that fail after there is a read/write dependency while unlocking nodes.
The test file adds a test that replicates the read/write dependency by unlocking nodes (similar to test_nodes_race.py)
Signed-off-by: Aishwarya Mathuria <amathuri@redhat.com>

controllers/nodes: Add retry and rollback for read requests

---

.github/workflows/ci.yml
requirements.txt
tox.ini

This could replace our Jenkins tests, while also allowing us to trivially test multiple python versions.

Add GitHub Actions definition for CI

---

Dockerfile

This is more about moving away from Docker Hub than anything else,
because its rate limiting makes automated image building difficult.
At first I tried Fedora images, but Quay's security scanner does not
support them. I would have used Alpine, but their official images are
also only at Docker Hub. Red Hat's ubi8-minimal image should work.

Dockerfile: Switch to UBI8 base image

---

Dockerfile
alembic/versions/266e6f3efd94_index_run_name.py
container_start.sh
paddles/models/runs.py

This has actually been running in production for a couple weeks without incident.

models.Run: Index the name column

---

gunicorn_config.py

This fixes a startup failure with podman

gunicorn_config.py: Don't log to files by default

---

paddles/controllers/nodes.py

On teuthology side at least for vms the lock/unlock mechanism still needs some records in return object like machine_type and is_vm:
https://github.com/ceph/teuthology/blob/main/teuthology/lock/cli.py#L168
https://github.com/ceph/teuthology/blob/main/teuthology/lock/cli.py#L174
Fixes: fb1c596bd68a559bb504a80dce39966cc6578c45

controllers/nodes: add missing records for return objects

---

paddles/controllers/jobs.py
paddles/controllers/root.py

This adds an endpoint to list jobs at new `/job` endpoint. By default, it returns latest posted jobs. We can add filter for description and status. 
Example:
`/jobs/?description=nvmeof/basic/{base/install%20centos_latest%20clusters/4-gateways-2-initiator%20conf/{disable-pool-app}%20workloads/nvmeof_scalability}&count=10&page=1`

controllers/jobs: Add JobsListController

---

paddles/controllers/jobs.py

Change 'description' filter from exact match
to checking for substring.
Add filter by build branch, sha1, username,
and posted_before/after.
Use-case examples:
- jobs/?posted_before=2025-11-03&posted_after=2025-02-20
- jobs/?posted_before=2025-11-03
- jobs/?description=teuthology&user=root

paddles/controllers/jobs.py: Add filters to JobsListController

---

paddles/models/runs.py
paddles/tests/models/test_runs.py

It's already part of the schema.

Run: Add 'priority' to returned fields

---

paddles/controllers/runs.py
paddles/models/runs.py
paddles/tests/models/test_runs.py

Related (but not dependent) PR: https://github.com/ceph/teuthology/pull/2065

models/runs.py: Add flavor to runs output
